version: "3.8"
services:
 sql:
  image: postgres:latest
  environment:
   POSTGRES_USER: localdb
   POSTGRES_PASSWORD: localdb
   POSTGRES_DB: users
  ports:
   - 54329:5432
  volumes:
   - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
